In [2]:
#Numpy array attributes
import numpy as np
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(10, size=6) #one-dimensional array
x2 = np.random.randint(10, size=(3, 4)) #two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) #three-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [4]:
print("dtype:", x3.dtype)

dtype: int64


In [5]:
print("itemsize: ", x3.itemsize, "bytes") #size of each element of the array in bytes
print("nbytes: ", x3.nbytes, "bytes") #total size of the array in bytes

itemsize:  8 bytes
nbytes:  480 bytes


In [6]:
#Array indexing: accessing single elements
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
#in multi-dimensional arrays:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
x2[0,0]

3

In [10]:
x2[2, -1]

7

In [11]:
#values can be modified the same way 
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [12]:
#array slicing: accessing subarrays

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [18]:
x[5:] #elements after the 5th element

array([5, 6, 7, 8, 9])

In [19]:
x[1::2] #every other element starting at index 1

array([1, 3, 5, 7, 9])

In [20]:
x[::-1] #all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
#Multidimensional arrays
x2[:2, :3] #two rows three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [22]:
x2[0:, ::2] #all rows, every other columns

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [23]:
x2[::-1, ::-1] #reverse all together

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [24]:
#accesing single rows and columns using slicing and index notation mix
x2[:, 0] #accesing first column

array([12,  7,  1])

In [25]:
x2[0, :] #accessing first row

array([12,  5,  2,  4])

In [26]:
x2[0] #equivalent to x2[0, :]

array([12,  5,  2,  4])

In [30]:
#subarrays are no-copy views of the original array
#changes in the view will affect the original
#we can explicitly copy arrays to avoid this behavior
x2_sub = x2[:2, :2].copy()
print(x2_sub)

[[12  5]
 [ 7  6]]


In [31]:
x2_sub[0,0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
#reshaping arrays
grid = np.arange(1,10).reshape(3,3) #the reshape dimension need to match the reshaped array

In [33]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
#conversion of onedimensional array to multidimensional array
x = np.array([1,2,3])

#row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [37]:
x.ndim

1

In [38]:
#row vector via new axis
x[np.newaxis, :]

array([[1, 2, 3]])

In [41]:
x.shape

(3,)

In [42]:
#column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [43]:
x.shape

(3,)

In [45]:
x.ndim

1

In [46]:
#column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [47]:
#array concatenation
x = np.array([1,2,3])
y = np.array([3,4,5])
np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

In [48]:
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  4,  5, 99, 99, 99])

In [49]:
#concatenate multidimensional array
grid = np.array([[9,8,7],
                 [6,5,4]])
np.concatenate([grid,grid])

array([[9, 8, 7],
       [6, 5, 4],
       [9, 8, 7],
       [6, 5, 4]])

In [50]:
#concatenate along the second axis
np.concatenate([grid,grid], axis = 1)

array([[9, 8, 7, 9, 8, 7],
       [6, 5, 4, 6, 5, 4]])

In [51]:
#vertically stack arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [52]:
#horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [57]:
#splitting arrays
x = np.array([1,2,3,99,99,3,2,1])
x1, x2, x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [61]:
#spltting vertically and horizontally
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [66]:
left, right = np.hsplit(grid, [2])
print(right)
print(left)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
