In [1]:
#Python lists are more than just lists
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
type(L2[0])

str

In [6]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [7]:
#Fixed-type array in python
import array 
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import numpy as np

In [10]:
#Creating arrays from python lists
#integer array
np.array([1,2,3,4,5]) #numpy is constrained to arrays that all contains the same type

array([1, 2, 3, 4, 5])

In [12]:
np.array([3.14, 4, 2, 3]) #numpy will upcast if possible

array([3.14, 4.  , 2.  , 3.  ])

In [13]:
np.array([1,2,3,4], dtype='float32') #we can explicitly set the data type of the resulting array

array([1., 2., 3., 4.], dtype=float32)

In [14]:
#nested lists result in multi-dimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#creating arrays from scratch (more efficient for larger arrays)

In [15]:
#Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
#create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
#create an array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
#(this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
#create an array of five values evenly spaced between 0 and 1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
#create a 3x3 array of uniformly distributed 
#random values between 0 and 1
np.random.random((3,3))

array([[0.21605918, 0.13369733, 0.95535234],
       [0.04760354, 0.57987949, 0.18480678],
       [0.95882996, 0.85958307, 0.05275422]])

In [27]:
#create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[7, 4, 3],
       [9, 7, 2],
       [5, 0, 0]])

In [28]:
#create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#create an uninitialized array of three integers
#the values will be whatever happens to already exist  at that memory location
np.empty(3)

array([1., 1., 1.])

In [ ]:
#Numpy standard data types are very similar to C data types because numpy is build in C